services:
  - type: web
    name: wa-sender-backend
    runtime: node
    rootDir: backend
    buildCommand: apt-get install -y google-chrome-stable && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: wa-session
