services:
  - type: web
    name: wa-sender-backend
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: wa-session
      mountPath: /opt/render/project/src/wa-session
      sizeGB: 1
